#!/usr/bin/env python3
"""Generates the driver and the harness for the audio gate.

    audio-assert-drive-gen.py OUT-DRIVE.pd OUT-HARNESS.pd STATEDIR WAVPATH

⛔ THE FIRST SIGNAL-DOMAIN GATE IN THIS PROJECT. Every other one asserts on
MESSAGES; nothing has ever read a signal back. The audio path is six boxes and
four `#X connect` lines at the end of u_root.pd -- r~ inL to throw~ outL, the
same on the right, and two level taps -- and a broken rewiring there is silent.
It would surface as no sound at a venue.

⛔ IT INSTANTIATES u_root DIRECTLY AND NOT main-dev.pd, and that is forced rather
than chosen. catch~ must be uniquely defined and u_mother-stub already holds
catch~ outL and catch~ outR, so a driver loaded beside main-dev.pd cannot add its
own -- Pd would refuse the second one and the recording would be silent. u_root
on its own loads clean: main-dev.pd is only the stub plus u_root, and every
mother name its children use is an ordinary undefined receive.

⚠️ 220 Hz LEFT AND 330 Hz RIGHT, the same split u_mother-stub uses so the rig
stays readable by ear as well as by number. ⛔ THE FREQUENCIES ARE THE POINT: L
and R being swapped is the failure that matters most -- the TRS Y-cable makes L
the SP-404's drums and R its fx, adc~ 1 is the tip, item 11 -- and amplitude
alone cannot see a swap because both channels carry the same level.

⚠️ ONE RECORDING, FOUR SEGMENTS, rather than four runs. writesf~ opens once and
the driver changes what is feeding it on a schedule, so the analyser cuts the
file by time. Guard bands of 300 ms sit either side of every boundary, because a
message-domain start is not sample-aligned with anything.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 40

# ⛔ THE AMPLITUDE, AND THE ANALYSER KNOWS IT. Unity is the third assertion and
# it cannot be checked without a number to compare against. 0.25 leaves 12 dB of
# headroom, so a passthrough that accidentally summed both channels would still
# be inside the file's range and would show up as a level error rather than as
# clipping -- which is the failure mode that is actually diagnosable.
AMP = 0.25

# Seconds from the start of the recording. Kept here because the analyser
# imports them: two copies of this table is how a gate comes to measure the
# wrong segment and report it with total confidence.
REC_MS = 2000
SEGMENTS = [("silence", 0.0, 1.0), ("both", 1.0, 3.0),
            ("left", 3.0, 5.0), ("right", 5.0, 7.0), ("tail", 7.0, 8.0)]
GUARD = 0.3


def _seq(wav):
    at = lambda s: REC_MS + int(s * 1000)
    return [
        # ⚠️ DSP AND THE FILE FIRST, and the open before the start -- writesf~
        # silently writes nothing to a file it was never given.
        (300, "DSP", ["\\; pd dsp 1"], GAP),
        (REC_MS, "REC", ["\\; aud-cmd open %s" % wav, "\\; aud-cmd start"], GAP),

        (at(1.0), "BOTH", ["\\; aud-l %g" % AMP, "\\; aud-r %g" % AMP], GAP),
        (at(3.0), "LEFT", ["\\; aud-r 0"], GAP),
        (at(5.0), "RIGHT", ["\\; aud-l 0", "\\; aud-r %g" % AMP], GAP),
        (at(7.0), "TAIL", ["\\; aud-r 0"], GAP),

        # ⛔ STOP BEFORE QUIT. writesf~ flushes and fixes up the WAV header on
        # stop; killed mid-write it leaves a file whose declared length is a lie,
        # and the analyser would read a truncated segment as silence.
        (at(8.0), "STOP", ["\\; aud-cmd stop"], GAP),
        (at(9.0), "DONE", [], GAP),
    ]


BLURB = ("audio-assert-drive -- GENERATED by audio-assert-drive-gen.py. Do not edit "
         "this file. It turns two oscillators on and off in the harness beside it "
         "and records u_root's OUTPUT to a soundfile: both channels \\, then left "
         "alone \\, then right alone.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/audio-assert.sh \\, never by hand. It needs the "
    "harness patch loaded alongside \\, which is what holds the catch~ pair and the "
    "writesf~ -- on its own this drives receives nothing is listening to and writes "
    "no file at all.",

    "⛔ THIS GATE RUNS WITH REAL DSP AND NO -noaudio. The whole subject is a signal "
    "\\, so a run that never computed one would assert on an empty file. The eleven "
    "seconds are real time by construction and a faster machine does not help.",
]

HARNESS_BLURB = (
    "audio-assert-harness -- GENERATED by audio-assert-drive-gen.py. Do not edit "
    "this file. It instantiates u_root ALONE -- not main-dev.pd \\, because "
    "u_mother-stub already defines catch~ outL and catch~ outR and catch~ must be "
    "unique -- feeds its two input sends from a pair of oscillators \\, and records "
    "what comes back out of it.")

HARNESS_NOTE = (
    "⛔ THIS IS THE ONLY PLACE IN THE PROJECT THAT READS A SIGNAL BACK. u_root's "
    "audio path is r~ inL to throw~ outL and the same on the right \\, plus two "
    "u_level taps -- four cords \\, no gain \\, no stages until v0.4. So the file "
    "written here should be the file sent in \\, channel for channel and sample for "
    "sample. ⚠️ aud-l \\, aud-r and aud-cmd are bare globals outside the C-2 "
    "allowlist \\, exactly like t-ctlin and clk-snap: this file exists only in a "
    "scratch directory and is thrown away.")


def write_harness(path, statedir):
    B, C = [], []

    def obj(x, y, s):
        B.append("#X obj %d %d %s;" % (x, y, s)); return len(B) - 1

    def txt(x, y, s, w):
        B.append("#X text %d %d %s, f %d;" % (x, y, s, w)); return len(B) - 1

    txt(20, 20, HARNESS_BLURB, 92)

    # ⚠️ THE SAME FIVE CREATION ARGUMENTS main-dev.pd PASSES, with only the state
    # directory changed. Pd 0.49 does not warn about a wrong argument count at
    # all, so a short list here would load in perfect silence and every channel
    # assertion would be about a differently-configured instrument.
    root = obj(20, 260, "u_root 17 1 %s 33 49" % statedir)

    osc_l = obj(20, 420, "osc~ 220")
    amp_l = obj(20, 470, "*~ 0")
    r_l = obj(200, 420, "r aud-l")
    snd_l = obj(20, 520, "s~ inL")
    C += [(osc_l, 0, amp_l, 0), (r_l, 0, amp_l, 1), (amp_l, 0, snd_l, 0)]

    osc_r = obj(500, 420, "osc~ 330")
    amp_r = obj(500, 470, "*~ 0")
    r_r = obj(680, 420, "r aud-r")
    snd_r = obj(500, 520, "s~ inR")
    C += [(osc_r, 0, amp_r, 0), (r_r, 0, amp_r, 1), (amp_r, 0, snd_r, 0)]

    cat_l = obj(980, 420, "catch~ outL")
    cat_r = obj(1180, 420, "catch~ outR")
    cmd = obj(1400, 420, "r aud-cmd")
    wsf = obj(980, 540, "writesf~ 2")
    C += [(cat_l, 0, wsf, 0), (cat_r, 0, wsf, 1), (cmd, 0, wsf, 0)]

    txt(20, 640, HARNESS_NOTE, 92)

    out = ["#N canvas 20 20 1900 900 12;"] + B \
        + ["#X connect %d %d %d %d;" % t for t in C]
    with open(path, "w") as fh:
        fh.write("\n".join(out) + "\n")
    return len(B), len(C)


if __name__ == "__main__":
    if len(sys.argv) < 5:
        sys.exit("usage: audio-assert-drive-gen.py OUT-DRIVE.pd OUT-HARNESS.pd "
                 "STATEDIR WAVPATH  (run it through test/gate/audio-assert.sh)")
    seq = _seq(sys.argv[4])
    w, b, c = D.build(sys.argv[1], seq, tag="AUDIO", taps=["disp"],
                      quit_ms=REC_MS + 10000, blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
    hb, hc = write_harness(sys.argv[2], sys.argv[3])
    print("%s  u_root + 2 osc~ + writesf~  %d boxes  %d connects"
          % (sys.argv[2], hb, hc))
