#!/usr/bin/env python3
"""Generates BOTH files the c_clock gate needs: the timed driver and a harness.

    clock-assert-drive-gen.py OUT-DRIVE.pd OUT-HARNESS.pd

⛔ c_clock PUBLISHES ON NO BUS, WHICH IS WHY THIS GATE NEEDS A HARNESS. Its whole
output is four outlets and one `[s err]`, so there is nothing for a tap to
listen to -- every other gate here asserts on a bus because every other subject
writes to one. The harness instantiates three c_clocks and puts a [print] on each
message outlet, which is the only way to read an outlet from outside.

⛔ AND IT DOES NOT LOAD main-dev.pd AT ALL. Three instances of the subject and
nothing else: no u_tempo publishing its own tempo, no g_grid consuming a beat, no
boot sequence. c_clock takes its tempo from a bus the driver can write directly,
so the whole instrument would be scenery -- and scenery is what makes a gate slow
and its failures ambiguous.

THE THREE INSTANCES, and each one is a different question:

    c_clock 1 8      the deployed shape -- u_root holds exactly this
    c_clock 1.5 4    a DIFFERENT rate and a different bar, which is what poly-
                     tempo means. Its beat count against the first is the
                     strongest check here, because a ratio cancels the scheduler
    c_clock 0 0      both arguments nonsense. Corrected to 1 and 4 immediately
                     and reported on err at 2 s, so it must end up beating in
                     step with the first one

⚠️ clk-snap IS A BARE GLOBAL OUTSIDE THE C-2 ALLOWLIST, exactly like t-notein and
t-ctlin, and for the same reason: it exists only in a generated harness that
lives in a scratch directory and is thrown away. Nothing in Cut It/ contains it.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 40

# ⛔ THE COUNTING WINDOW, AND IT IS LONG ON PURPOSE. threshold~ fires once per
# DSP block, so a window's edges are not sample-aligned and a short window turns
# a one-block boundary effect into a large fraction of the count. Six seconds at
# 120 BPM is 12 beats at ratio 1, where +/-1 is noise rather than a verdict.
RATE_MS = 6000

# 20 snapshots 30 ms apart = 600 ms = 1.2 beats at 120 BPM, so the ramp is
# guaranteed to be caught at both ends of its sweep rather than sampled by luck.
SNAPS = 20

SEQ = [
    # ⚠️ DSP FIRST, AND IT IS NOT OPTIONAL. Everything below hangs off phasor~
    # through threshold~; with DSP off the whole run is silent and every count is
    # zero, which is a very confident way of asserting nothing.
    (300, "DSP", ["\\; pd dsp 1", "\\; tempo 120"], GAP),

    # ⛔ start IS WHAT ALIGNS THE THREE INSTANCES TO EACH OTHER. After it, the
    # next pulse is pulse 0 of beat 1 of bar 1 in all three, so the counts below
    # are measured from a common origin rather than from whenever each was born.
    (2000, "START", ["\\; start bang"], GAP),

    (2500, "RATE", [], GAP),
    (2500 + RATE_MS, "RATE-END", [], GAP),

    # --- the signal outlet, sampled across more than one full cycle --------
    (9200, "PHASE", ["\\; clk-snap bang"] * SNAPS, 30),

    # --- ⛔ stop DOES NOT HALT ---------------------------------------------
    # A running phasor nobody reads is silent, and halting it is the consumer's
    # business -- the same reason u_tempo keeps sending clock while stopped.
    (10200, "STOP", ["\\; stop bang"], GAP),
    (10700, "AFTER-STOP", [], GAP),
    (12700, "AFTER-STOP-END", [], GAP),

    # --- and start resets the beat number ----------------------------------
    # ⛔ 13250 IS ARITHMETIC, NOT A ROUND NUMBER. The start at 2000 ms reset the
    # phase, so beats land on 2000 + k*500 at 120 BPM; 13250 is 22.5 beats past
    # it, which is as far from a beat as this schedule can put a window edge.
    # That matters because the reset beat arrives ~10 ms after the start message
    # -- the pulse counter is set to 23, so the very next pulse is pulse 0 of
    # beat 1 -- and the assertion is that this window contains that beat and
    # nothing else. A window edge landing on a beat would put a stray number in
    # front of it and the gate would be reporting the schedule, not the reset.
    (13250, "RESTART", ["\\; start bang"], GAP),
    (13600, "AFTER-RESTART", [], GAP),

    (15400, "DONE", [], GAP),
]
QUIT_MS = 16000

BLURB = ("clock-assert-drive -- GENERATED by clock-assert-drive-gen.py. Do not edit "
         "this file. It drives three c_clock instances in the harness beside it: the "
         "tempo and the transport \\, a snapshot burst across the signal outlet \\, "
         "and a stop that must NOT halt anything.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/clock-assert.sh \\, never by hand. It needs the "
    "harness patch loaded alongside it -- on its own it drives three buses that "
    "nothing is listening to \\, and every count comes back zero.",

    "⛔ THIS GATE RUNS WITH DSP ON \\, which is why it is one of the slower ones. "
    "The beat comes out of threshold~ on a wrap~ of a phasor~ \\, so a -noaudio run "
    "would assert on a clock that never ticks. A faster machine does not help: the "
    "sixteen seconds are real time by construction.",
]

# ---------------------------------------------------------------------------
HARNESS_BLURB = (
    "clock-assert-harness -- GENERATED by clock-assert-drive-gen.py. Do not edit "
    "this file. THREE c_clock INSTANCES AND A PRINT ON EVERY MESSAGE OUTLET \\, "
    "which is the only way to read an outlet from outside: c_clock publishes on no "
    "bus \\, so unlike every other subject in test/gate/ it cannot be tapped.")

HARNESS_NOTE = (
    "⛔ OUTLET ORDER IS THE CONTRACT AND IT IS POSITIONAL. Left to right: the raw "
    "beat PHASE as a signal \\, a beat bang \\, the beat number within the bar \\, "
    "and a bar bang. Pd orders an abstraction's outlets by the X POSITION of its "
    "outlet boxes \\, not by the order they appear in the file \\, so a box moved "
    "sideways in c_clock.pd silently renumbers all four. That is what these prints "
    "are pinned to. ⚠️ clk-snap is a bare global outside the C-2 allowlist \\, and "
    "that is safe: this file exists only in a scratch copy.")


def write_harness(path):
    """Three instances, a print on each message outlet, one snapshot~ on a signal."""
    B, C = [], []

    def obj(x, y, s):
        B.append("#X obj %d %d %s;" % (x, y, s)); return len(B) - 1

    def txt(x, y, s, w):
        B.append("#X text %d %d %s, f %d;" % (x, y, s, w)); return len(B) - 1

    txt(20, 20, HARNESS_BLURB, 92)

    # --- instance A: the deployed shape, and the only one read in full -----
    a = obj(20, 260, "c_clock 1 8")
    a_beat = obj(20, 560, "print CLKA-BEAT")
    a_num = obj(280, 620, "print CLKA-NUM")
    a_bar = obj(540, 680, "print CLKA-BAR")
    snap = obj(800, 380, "snapshot~")
    a_ph = obj(800, 440, "print CLKA-PHASE")
    rsnap = obj(1000, 320, "r clk-snap")
    C += [(a, 1, a_beat, 0), (a, 2, a_num, 0), (a, 3, a_bar, 0),
          (a, 0, snap, 0), (rsnap, 0, snap, 0), (snap, 0, a_ph, 0)]

    # --- instance B: a different rate and a different bar ------------------
    b = obj(1300, 260, "c_clock 1.5 4")
    b_beat = obj(1300, 560, "print CLKB-BEAT")
    b_num = obj(1500, 620, "print CLKB-NUM")
    b_bar = obj(1700, 680, "print CLKB-BAR")
    C += [(b, 1, b_beat, 0), (b, 2, b_num, 0), (b, 3, b_bar, 0)]

    # --- instance C: both arguments nonsense -------------------------------
    c = obj(2000, 260, "c_clock 0 0")
    c_beat = obj(2000, 560, "print CLKC-BEAT")
    c_num = obj(2200, 620, "print CLKC-NUM")
    c_bar = obj(2400, 680, "print CLKC-BAR")
    C += [(c, 1, c_beat, 0), (c, 2, c_num, 0), (c, 3, c_bar, 0)]

    txt(20, 800, HARNESS_NOTE, 92)

    out = ["#N canvas 20 20 2600 1000 12;"] + B \
        + ["#X connect %d %d %d %d;" % t for t in C]
    with open(path, "w") as fh:
        fh.write("\n".join(out) + "\n")
    return len(B), len(C)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit("usage: clock-assert-drive-gen.py OUT-DRIVE.pd OUT-HARNESS.pd  "
                 "(run it through test/gate/clock-assert.sh, which passes both)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="CLK", taps=["err"],
                      quit_ms=QUIT_MS, blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
    hb, hc = write_harness(sys.argv[2])
    print("%s  3 instances  %d boxes  %d connects" % (sys.argv[2], hb, hc))
