#!/usr/bin/env python3
"""Generates the timed driver for the display gate, into the scratch path given.

It pushes onto mode, disp, err, tempo, start and panic exactly as a controller
would, and touches nothing in the deployed patch.

⚠️ DSP IS OFF FOR THE FIRST WINDOWS ON PURPOSE. With no clock the grid has
nothing to redraw, so `idle-dsp-off` is what proves the dirty flag really gates
the repaint: the boot frame, and then silence. Everything after it needs DSP,
because the beat row hangs off threshold~.

⛔ THE 300 ms WINDOW EXISTS BECAUSE THE REST OF THIS SCHEDULE CANNOT FALSIFY THE
BOOT. Every other window here is seconds in, by which time g_grid has taken
ownership and the arbiter is settled -- so nothing in the old version of this
driver could see anything about the instrument's first three seconds. A mode set
at 300 ms, before the grid paints at all, must still be the mode the first
painted frame shows. That is the display's form of item 234.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 20

SEQ = [
    # ⛔ BEFORE the grid owns the surface. mode-5 is chosen because nothing else
    # in this run uses it, so a lamp at index 95 later can only have come from here.
    (300, "EARLY-MODE", ["\\; mode perform mode-5"], GAP),
    (4000, "idle-dsp-off", [], GAP),
    (8000, "dsp-on", ["\\; pd dsp 1"], GAP),
    # ⚠️ TEMPO ONLY. The mode is deliberately NOT re-sent here -- the next window
    # asserts that the one set at 300 ms survived, and setting it again would make
    # that assertion vacuous.
    (8600, "settling", ["\\; tempo 120"], GAP),
    (11000, "home-early-mode", [], GAP),
    (14000, "home-mode-1", ["\\; mode compose mode-1"], GAP),
    (17000, "home-mode-4", ["\\; mode perform mode-4"], GAP),
    (20000, "modal-45", ["\\; disp grid modal 45"], GAP),
    (23000, "warn-ignored", ["\\; err warn u_bench quiet"], GAP),
    (26000, "alert-red", ["\\; err fail u_bench boom"], GAP),
    # the alert TTL is 2 s, so this window opens after it has expired
    (28500, "alert-expired", [], GAP),
    (31000, "home-again", ["\\; disp grid modal-off"], GAP),
    (34000, "beat-row", ["\\; start bang"], GAP),
    (41000, "after-panic", ["\\; panic bang"], GAP),
    (45000, "done", [], GAP),
]
QUIT_MS = 46000

BLURB = ("display-assert-drive -- GENERATED by display-assert-drive-gen.py. Do not "
         "edit this file. It drives the display arbiter: the dirty flag \\, the home "
         "layer and its mode lamp \\, a modal claiming the whole surface \\, an alert "
         "outranking it and expiring back to it \\, the beat row walking \\, and the "
         "surface going silent after a panic.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/display-assert.sh \\, never by hand -- the whole point "
    "is that [midiout] has been rewritten to [t_midiout] in a scratch copy first \\, so "
    "every byte the patch emits reaches stdout. Run it against the real Cut It and the "
    "frames are invisible and every assertion passes vacuously.",

    "⚠️ THIS RUN NEEDS DSP AND THEREFORE TAKES 46 SECONDS. The beat row hangs off "
    "threshold~ in c_clock \\, so a -noaudio run would assert on a grid that never "
    "moves. It is the only gate in the suite that costs more than ten seconds \\, and "
    "the beat row is the reason.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: display-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/display-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="GRID",
                      taps=[], quit_ms=QUIT_MS, blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
