#!/usr/bin/env python3
"""Generates the timed driver for the error-bus gate, into the scratch path given.

⛔ THE CENTRAL CLAIM HERE IS ONE NOBODY HAS EVER TESTED HEADLESSLY: that perform
mode suppresses `warn` but NEVER suppresses `fail`. It was bench prose only.
plan-v04.md notes that a mode split weighted toward perform silently quietens the
error display -- a failure whose first symptom is a venue, at the moment the
instrument is least able to tell you anything.

⚠️ EVERY MODE WINDOW SETS THE MODE AND RAISES IN THE SAME WINDOW, one action
apart. u_err's spigot is set by a [route] on the mode bus with no delay in front
of it, so a mode set in an earlier window would test the state the mode left
behind rather than the transition -- and both are worth knowing, which is why the
two `fail` windows straddle a mode change instead of resetting it.

⛔ THE VERBOSE DEFAULT IS TESTED FIRST AND CANNOT BE TESTED TWICE. Nothing can
put u_err back into "no mode has ever arrived", so the 300 ms window is the only
chance the whole run has at it. That is also the state the instrument boots in.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 40

SEQ = [
    # ⛔ BEFORE ANY MODE HAS ARRIVED. The default is verbose, and this is the one
    # window in the run that can say so -- there is no way back to it.
    (300, "DEFAULT", ["\\; err warn u_gate before-mode"], GAP),

    # --- compose: everything shows ----------------------------------------
    (5000, "COMPOSE-WARN",
     ["\\; mode compose mode-1", "\\; err warn u_gate compose-warn"], GAP),
    (5700, "COMPOSE-FAIL", ["\\; err fail u_gate compose-fail"], GAP),

    # --- ⛔ perform: warn is dropped and fail is NOT ------------------------
    (6400, "PERFORM-WARN",
     ["\\; mode perform mode-4", "\\; err warn u_gate perform-warn"], GAP),
    # ⛔ THE ONE THAT MATTERS. Still in perform -- the mode is deliberately not
    # re-sent, so this asserts the state the previous window left behind.
    (7100, "PERFORM-FAIL", ["\\; err fail u_gate perform-fail"], GAP),

    # --- back to compose, so the filter is proved to be reversible ---------
    (7800, "BACK-TO-COMPOSE",
     ["\\; mode compose mode-2", "\\; err warn u_gate back-warn"], GAP),

    # --- a two-atom mode, which is what u_map actually sends ---------------
    # ⚠️ route matches on the SELECTOR, so `perform mode-6` must filter exactly
    # as a bare `perform` does. u_map has sent the two-atom form since Phase 6
    # and the filter was never changed for it -- that is a claim, not a fact,
    # until something drives both forms.
    (8500, "TWO-ATOM-MODE",
     ["\\; mode perform mode-6", "\\; err warn u_gate two-atom"], GAP),

    # --- ⛔ info: LOGGED AND NEVER DRAWN ------------------------------------
    # The third level, and the only one whose correct result is that the screen
    # does nothing. ⚠️ IT IS RAISED IN COMPOSE, which is the state the window
    # above leaves behind -- raising it in perform would be answered by the mode
    # filter and would prove nothing about the level. So the mode is set back
    # first, and `back-warn` in the same window is the LIVENESS WITNESS: it
    # proves the screen was willing to draw at that moment, which is what stops
    # "info drew nothing" being satisfied by a dead display.
    (9200, "INFO",
     ["\\; mode compose mode-3", "\\; err warn u_gate info-witness",
      "\\; err info u_gate info-quiet"], GAP),

    # --- a level that is none of the three ---------------------------------
    (9900, "BAD-LEVEL", ["\\; err chatty u_gate bad-level"], GAP),

    (10600, "DONE", [], GAP),
]
QUIT_MS = 11300

BLURB = ("err-assert-drive -- GENERATED by err-assert-drive-gen.py. Do not edit this "
         "file. It drives u_err's mode filter: warn suppressed in perform and passed "
         "in compose \\, fail passed in BOTH \\, the two-atom mode form \\, and a "
         "level that is neither.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/err-assert.sh \\, never by hand. The gate taps disp "
    "and err \\, and it also reads the RAW capture for u_err's own unconditional "
    "[print err] -- which is the half that proves the LOG is never filtered even when "
    "the SCREEN is.",

    "⛔ fail MUST PASS IN PERFORM MODE. u_err's spigot sits on the warn branch only "
    "and fail is unspigoted \\, which is a one-cord distinction that nothing on the "
    "instrument would report if it were wrong: the display would simply go quiet \\, "
    "and the first place you would find out is a venue.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: err-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/err-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="ERR", taps=["disp", "err"],
                      quit_ms=QUIT_MS, blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
