#!/usr/bin/env python3
"""Generates the timed driver for the boot-sequence gate.

⚠️ THIS DRIVER DRIVES ALMOST NOTHING, AND THAT IS THE POINT. u_init's whole
subject is what happens WITHOUT anybody touching the instrument: it owns the
ordered startup, every stage hangs off one loadbang, and the only correct
stimulus is to load the patch and watch. The windows here exist to divide the
boot into before and after, not to poke it.

⛔ THE STRONG ASSERTIONS ARE ABOUT ORDER, NOT ABOUT MILLISECONDS. ref/module/boot.md
says the stage timings are guesses with evidence rather than measurements (item
266), so a gate that pinned them would go red the first time somebody lengthened
a delay for a real reason -- and would be asserting the implementation back at
itself. What must hold is the SEQUENCE, and that the two-stage MIDI gating really
is two stages.

⚠️ ONE WINDOW OPENS AT 1000 ms PURELY TO SEPARATE "AT LOADBANG" FROM "LATER".
mother's own binary pushes midiInGate 1 over OSC about half a second after the
patch loads, which overwrote the value sent at loadbang -- so u_init sends it
twice and the SECOND one is the one that works. A capture with no window between
them cannot tell one send from two.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 40

SEQ = [
    # Everything before this mark is the loadbang stage: modal booting, the
    # first midiInGate 0, midiOutGate 0 and wire.sh. lib_assert buckets it as
    # "PRE", which is exactly the distinction this window creates.
    (1000, "AFTER-LOADBANG", [], GAP),

    # Opened before the launchpad stage and before the restore, so neither can
    # be read out of a window that had already started.
    (2500, "MID-BOOT", [], GAP),

    # Long after the last stage. If anything is still arriving here, the
    # sequence did not finish where it claims to.
    (5000, "SETTLED", [], GAP),
    (7000, "QUIET", [], GAP),

    (8000, "DONE", [], GAP),
]
QUIT_MS = 8600

BLURB = ("init-assert-drive -- GENERATED by init-assert-drive-gen.py. Do not edit "
         "this file. It drives NOTHING: u_init's subject is what happens without "
         "anybody touching the instrument \\, so these windows only divide the boot "
         "into before and after.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/init-assert.sh \\, never by hand. The gate copies a "
    "counting stub over shell.pd in its scratch copy \\, which is the only way to see "
    "that wire.sh was invoked -- the real [shell] does not exist on a Mac and "
    "mac-stubs/shell.pd deliberately swallows the command.",

    "⛔ IT ALSO SEEDS THE STATE FILES. The restore stage is u_init's last outlet \\, "
    "and against empty files it publishes nothing at all -- so the assertion that it "
    "fired would be answered by silence. Two known lines go in \\, one per store \\, "
    "and the restore has to replay both in the right order.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: init-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/init-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="INIT",
                      taps=["disp", "state", "midiInGate", "midiOutGate"],
                      quit_ms=QUIT_MS, blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
