#!/usr/bin/env python3
"""Generates the timed driver for the Launchpad gate, into the scratch path given.

⚠️ SHORT, AND WITH NO DSP. This gate asserts on two SysEx messages the device is
sent -- the mode switch at boot and the one on panic -- and neither needs a
clock, a beat row or a painted surface. It was part of a 46-second DSP run only
because it shared a gate with the display arbiter; on its own it costs 4 s.

⛔ THE ORDER IS AN ASSERTION, NOT AN ACCIDENT. Programmer Mode has to be entered
BEFORE anything is painted: LED writes sent in Live Mode do not appear, so a
patch that painted first and switched second would come up dark and look like a
broken grid. The driver therefore does nothing at all before the panic -- boot is
the whole first act, and the analyser reads its ordering out of the capture.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 20

SEQ = [
    # ⚠️ 2500 ms, and the number is not free. u_init's boot sequence puts the
    # Launchpad into Programmer Mode behind a delay measured in seconds -- see
    # ref/module/boot.md -- so a panic fired before that would find nothing to
    # undo and the gate would pass having tested nothing.
    (2500, "SETTLED", [], GAP),
    (3000, "PANIC", ["\\; panic bang"], GAP),
]
QUIT_MS = 4000

BLURB = ("launchpad-assert-drive -- GENERATED by launchpad-assert-drive-gen.py. Do "
         "not edit this file. It drives m_launchpad's own SysEx: Programmer Mode at "
         "boot \\, and Live Mode on panic. It paints nothing and needs no clock.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/launchpad-assert.sh \\, never by hand -- the whole "
    "point is that [midiout] has been rewritten to [t_midiout] in a scratch copy "
    "first \\, so every byte the patch emits reaches stdout.",

    "⛔ LIVE MODE ON PANIC IS THE ONE THAT COSTS A POWER CYCLE. A Launchpad left in "
    "Programmer Mode is stranded: it stops behaving like a Launchpad for every other "
    "program on the machine \\, and nothing on the Organelle can put it back. That is "
    "why panic hands the device back BY DESIGN and why the watchdog deliberately does "
    "not fight it.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: launchpad-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/launchpad-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="LP",
                      taps=[], quit_ms=QUIT_MS, blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
