#!/usr/bin/env python3
"""Generates the timed driver for the aux LED gate, into the scratch path given.

⚠️ THE SMALLEST DRIVER IN THE SUITE, for the smallest file in the patch. g_led is
34 lines: one route on the disp bus, a second on the state name, four message
boxes and a warning. It needs no DSP, no MIDI, no scratch rewrite and no clock --
only the disp bus, which every driver already has.

⛔ IT WAS ALSO THE ONLY MODULE WITH ZERO REFERENCES ANYWHERE UNDER test/. Its
page named display-assert.sh, which asserts on Launchpad SysEx and never touches
the LED at all.

⚠️ THE UNKNOWN-STATE WINDOW COMES AFTER A KNOWN ONE ON PURPOSE. "The LED is left
alone" can only be asserted against an LED that was demonstrably being driven a
moment earlier, so `running` is set first and the bad state has to fail to
disturb it.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 40

SEQ = [
    # ⛔ BEFORE THE BOOT SEQUENCE HAS FINISHED. g_led needs no table and no
    # restore, so it must answer from the first millisecond -- and u_init is
    # still pushing modal stages onto the same bus at this point, which is the
    # traffic a route with a loose match would swallow.
    (300, "EARLY", ["\\; disp led running"], GAP),

    # --- the four states, one window each ------------------------------
    (5000, "OFF", ["\\; disp led off"], GAP),
    (5700, "STOPPED", ["\\; disp led stopped"], GAP),
    (6400, "RUNNING", ["\\; disp led running"], GAP),
    (7100, "PANIC", ["\\; disp led panic"], GAP),

    # --- a state g_led does not know -----------------------------------
    (7800, "UNKNOWN", ["\\; disp led flashing"], GAP),

    # --- a disp selector that is not led at all ------------------------
    # ⚠️ g_led shares the bus with g_oled, g_grid and u_net. Every one of them
    # sees every message, so "it ignores what is not its own" is a real claim
    # and not a formality.
    (8500, "NOT-LED", ["\\; disp status v0-test"], GAP),

    (9200, "DONE", [], GAP),
]
QUIT_MS = 9900

BLURB = ("led-assert-drive -- GENERATED by led-assert-drive-gen.py. Do not edit this "
         "file. It drives g_led over the disp bus: the four states and their four "
         "mother values \\, a state it does not recognise \\, and a disp selector "
         "that is not its own.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/led-assert.sh \\, never by hand. The gate taps the "
    "led bus \\, which is mother's own name -- on the device mother is listening to "
    "it and here nothing is \\, so without the tap every assertion is answered by an "
    "empty list.",

    "⛔ stopped IS 5 \\, WHICH IS LIT \\, NOT 0. The whole point of the state is that "
    "a patch which is up but not running must not look identical to a patch that has "
    "died. Nothing else in the rig reports that \\, because the OLED goes dark too.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: led-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/led-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="LED",
                      taps=["led", "err", "disp"], quit_ms=QUIT_MS,
                      blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
