#!/usr/bin/env python3
"""Generates the timed driver for the map gate, into the scratch path it is given.

It pushes onto `param` and `mode` exactly as the m_ layers would. It asserts
nothing about any DEVICE -- it uses volca-cc only because a lookup has to land
somewhere, and what that destination then does with the value is
volca-assert's business.

⛔ 300 ms IS THE POINT OF THIS DRIVER, not a detail of it. Every window in the
gate this was split out of started at 2400 ms, and the comment said why: u_map
read its table at 2000. A schedule derived from the implementation cannot
falsify it -- so the gate had 23 green checks and could not see the boot race
that the hardware found. mother pushes knobs.txt at BOOT, the table and the mode
key were both still unset, the restored tempo was silently dropped, and the
instrument came up at 120 instead of the saved 57. Item 234.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 20

SEQ = [
    # ⛔ BEFORE u_map reads its table. The map must work from load.
    (300, "EARLY", ["\\; param og-knob-1 0.0958"], GAP),
    (2400, "TEMPO", ["\\; param og-knob-1 0.5"], GAP),
    (2600, "MAPPED", ["\\; param gk-cc 64"], GAP),
    # ⛔ BEFORE the mode switch. The bad row is keyed mode-1, so testing it after
    # switching to mode-4 makes it a LOOKUP MISS -- correctly silent, and nothing
    # to do with the guard it is meant to exercise.
    (4400, "BAD-DEST", ["\\; param gk-bad 100"], GAP),
    # ⚠️ AFTER 3.5 s ON PURPOSE. u_init restores saved state around then and
    # republishes mode; a switch before that is overwritten mid-run and the
    # mode-dependence check reads as broken when it is not. Item 232's other half.
    (5000, "MODE-4", ["\\; param xport-4 1"], GAP),
    (5200, "MODE-DEP", ["\\; param gk-cc 64"], GAP),
]
QUIT_MS = 6000

BLURB = ("map-assert-drive -- GENERATED by map-assert-drive-gen.py. Do not edit this "
         "file. It drives the mode table: the lookup at load \\, a mapped control "
         "reaching its destination \\, the same control in another mode doing nothing \\, "
         "and a row naming a destination that is not on u_map's route.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/map-assert.sh \\, never by hand. The gate appends its "
    "own rows to the mapping table in a SCRATCH COPY and rewrites the MIDI objects to "
    "printing stubs. Loaded on its own against the real patch it would emit real MIDI "
    "to whatever is plugged in \\, and half the windows would find no mapping at all.",

    "⚠️ THE STATE DIRECTORY IS THE GATE'S OWN AND MUST BE EMPTY. main-dev.pd passes "
    "/tmp \\, which every run on the machine shares -- and u_init restores saved state at "
    "about 3.5 s. A previous test that changed mode leaves mode in that file \\, the "
    "restore republishes it mid-run \\, and every row keyed to another mode stops matching "
    "from that instant. It cost a wrong diagnosis once already: item 232.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: map-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/map-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="MAP",
                      taps=["param", "err", "tempo"], quit_ms=QUIT_MS,
                      blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
