#!/usr/bin/env python3
"""Generates the timed driver for the nanoKONTROL gate, into the scratch path given.

⛔ IT DRIVES [t_ctlin], WHICH IS WHY THIS GATE CAN EXIST AT ALL. m_nano has no
inlets and reads no bus: its entire surface arrives through [ctlin], and there is
no bus behind a MIDI input. test/gate/lib-scratch.sh named the missing stub as
the blocker in writing for as long as this gate did not exist.

⚠️ THE ATOMS ARE IN OUTLET ORDER -- `t-ctlin <value> <controller> <channel>` --
because t_ctlin is an [unpack f f f] wired outlet-for-outlet, exactly like
t_notein. Reading it as channel-first gets every window backwards.

⛔ ONE t-ctlin REACHES ALL THREE REWRITTEN [ctlin] BOXES, so every message here is
offered to m_404 and m_launchpad as well as to m_nano. That is not noise to work
around: it is what makes the three channel blocks assertable against each other
rather than each one being trusted alone. The last two windows drive the OTHER
two devices' channels on purpose, so "the nano's channel produces no sp-cc" has a
liveness witness proving the stub reaches those boxes at all.

⛔ THE 300 ms WINDOW EXISTS BECAUSE THE REST OF THIS SCHEDULE CANNOT FALSIFY THE
BOOT. m_nano needs no table and no restore, so it must decode from the first
millisecond -- and item 234 was exactly a control that worked at 5 s and was
dropped at 300 ms. Every other window here is seconds in and could not tell.

⚠️ CHANNEL 2 IS SWEPT ACROSS FOUR CHANNELS WITH FOUR DIFFERENT VALUES. Pd
channels 17 and 18 both decode to `slider-2`, so a gate that drove the same value
on both could not tell one arriving twice from both arriving once.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 40

SEQ = [
    # --- before anything has settled ---------------------------------------
    (300, "EARLY", ["\\; t-ctlin 64 1 17"], GAP),

    # --- the channel gate: 17 and 18 in, everything else out ---------------
    # ⚠️ Each value is distinct so the analyser can say WHICH channel produced
    # the emit, not merely that some did.
    (5000, "CH-16", ["\\; t-ctlin 10 2 16"], GAP),
    (5700, "CH-17", ["\\; t-ctlin 11 2 17"], GAP),
    (6400, "CH-18", ["\\; t-ctlin 12 2 18"], GAP),
    (7100, "CH-19", ["\\; t-ctlin 13 2 19"], GAP),

    # --- the five name families, one window each ---------------------------
    (7800, "SLIDER", ["\\; t-ctlin 21 3 17"], GAP),
    (8500, "KNOB", ["\\; t-ctlin 22 15 17"], GAP),
    (9200, "BTN-T", ["\\; t-ctlin 127 22 17"], GAP),
    (9900, "BTN-B", ["\\; t-ctlin 127 34 17"], GAP),
    (10600, "XPORT", ["\\; t-ctlin 127 43 18"], GAP),

    # --- press only, and the release is the point --------------------------
    # Both halves in ONE window so the check is self-witnessing: nothing emitted
    # fails it and two emits fail it, so it cannot pass by the run dying.
    (11300, "PRESS-RELEASE",
     ["\\; t-ctlin 127 24 17", "\\; t-ctlin 0 24 17"], GAP),

    # --- a CC in the block that decodes to no known kind -------------------
    (12000, "UNMAPPED", ["\\; t-ctlin 99 55 17"], GAP),

    # --- ⛔ THE STALE-FLAG TRAP, BOTH ARMS ---------------------------------
    # m_nano clears is-cont and is-btn on the unmapped path, off the RIGHTMOST
    # outlets, before the error goes out. Without those clears the unmapped CC's
    # value would be emitted under the PREVIOUS control's name -- plausible,
    # wrong and silent. The two arms are needed because the two flags fail
    # differently: a stale is-cont leaks the raw value, a stale is-btn leaks a 1.
    (12700, "STALE-CONT",
     ["\\; t-ctlin 30 7 17", "\\; t-ctlin 99 55 17"], GAP),
    (13400, "STALE-BTN",
     ["\\; t-ctlin 127 26 17", "\\; t-ctlin 127 56 17"], GAP),

    # --- the other two devices' channel blocks, through the same stub ------
    (14100, "CH-404", ["\\; t-ctlin 77 20 33"], GAP),
    (14800, "CH-LP", ["\\; t-ctlin 55 30 1"], GAP),

    (15500, "DONE", [], GAP),
]
QUIT_MS = 16200

BLURB = ("nano-assert-drive -- GENERATED by nano-assert-drive-gen.py. Do not edit "
         "this file. It drives m_nano through t_ctlin: the channel gate \\, the five "
         "name families \\, buttons on press only \\, the unmapped-CC warning and the "
         "flag clears behind it \\, and the other two devices' channel blocks.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/nano-assert.sh \\, never by hand -- the whole point "
    "is that [ctlin] has been rewritten to [t_ctlin] in a scratch copy first. Against "
    "the real Cut It nothing reaches m_nano at all and every assertion passes "
    "vacuously.",

    "⛔ t-ctlin CARRIES <value> <controller> <channel> \\, in OUTLET order. The real "
    "[ctlin] fires channel \\, then controller \\, then value -- right to left -- and "
    "t_ctlin is an unpack wired outlet-for-outlet to reproduce that \\, so the channel "
    "gate is always set before the value is read. That ordering is the reason m_nano "
    "needs no delay object anywhere.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: nano-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/nano-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="NANO",
                      taps=["param", "disp", "err"], quit_ms=QUIT_MS,
                      blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
