#!/usr/bin/env python3
"""Generates the timed driver for the Organelle front-panel gate.

⚠️ IT DRIVES MOTHER'S OWN NAMES DIRECTLY -- `; knob1 0.25`, `; aux 1` -- because
that is exactly what mother.pd does on the device. m_organelle has no inlets and
no MIDI: five [r] boxes on reserved names is its entire input surface, so this is
the one m_ layer that needs no stub at all.

⛔ KNOB 1 IS MAPPED TO TEMPO IN EVERY MODE and knob 4 is mapped to nothing. Both
are deliberate choices of subject: knob 1 is the only way to assert item 242 --
that a knob's RAW position never reaches the screen, because the mapped value
belongs there -- and knob 4 is the only knob free to be driven to a bare 0
without a mapping reacting to it.

⚠️ THE 0 IS THE POINT OF THE KNOB-4 WINDOW. `change -1` rather than a bare
`change` is load-bearing: a bare change starts life holding 0, so a knob parked
at 0 would never publish and the parameter it feeds would sit at its default
forever. -1 cannot be a real value because mother's knobs are 0 to 1. Item 237,
measured rather than reasoned.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 40

SEQ = [
    # ⛔ BEFORE THE BOOT SEQUENCE HAS FINISHED. mother pushes knobs.txt at boot,
    # long before u_map's table used to be read -- which is precisely how item
    # 234 happened. m_organelle needs nothing from boot and must say so.
    (300, "EARLY", ["\\; aux 1"], GAP),

    # --- a mapped knob: param gets the control, the screen gets the meaning ---
    (5000, "KNOB1", ["\\; knob1 0.25"], GAP),
    # ⚠️ THE SAME VALUE AGAIN, in its own window, so the filter has something to
    # filter. Sent inside the window above it would be indistinguishable from one
    # message arriving late.
    (5700, "KNOB1-SAME", ["\\; knob1 0.25"], GAP),
    (6400, "KNOB1-NEW", ["\\; knob1 0.5"], GAP),

    # --- ⛔ A KNOB PARKED AT ZERO STILL PUBLISHES -------------------------
    (7100, "KNOB4-ZERO", ["\\; knob4 0"], GAP),

    # --- the other two, so all four names are asserted --------------------
    (7800, "KNOB23", ["\\; knob2 0.1", "\\; knob3 0.2"], GAP),

    # --- the aux button, which is the one control that still reports -------
    (8500, "AUX-PRESS", ["\\; aux 1"], GAP),
    (9200, "AUX-RELEASE", ["\\; aux 0"], GAP),

    # --- ⛔ THE KEYBOARD: ONE CONTROL PER KEY, AND A RELEASE IS A REAL EVENT ---
    # mother packs the keyboard into ONE two-float list -- pitch then velocity --
    # and param carries one value per control, so the pitch rides in the NAME.
    (9900, "KEY-ON", ["\\; notes 60 100"], GAP),
    # ⛔ VELOCITY 0 IS THE NOTE-OFF AND IT MUST PUBLISH. aux is press-only because
    # a button release means nothing; a key release is the event that stops the
    # sound, and a destination cannot act on what it is never told.
    (10600, "KEY-OFF", ["\\; notes 60 0"], GAP),
    # ⚠️ THE TOP KEY, because 60 alone would pass on a decode that ignored the
    # pitch entirely and hardcoded the lowest note.
    (11300, "KEY-TOP", ["\\; notes 84 40"], GAP),

    (12000, "DONE", [], GAP),
]
QUIT_MS = 12700

BLURB = ("organelle-assert-drive -- GENERATED by organelle-assert-drive-gen.py. Do "
         "not edit this file. It drives m_organelle over mother's own names: the four "
         "knobs through their change filters \\, a knob parked at zero \\, and the aux "
         "button on press only \\, and the 25-key keyboard on both press and release.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/organelle-assert.sh \\, never by hand. It asserts on "
    "param and disp \\, and without the taps every check is answered by an empty list.",

    "⛔ THE KNOBS DO NOT REPORT TO disp AND og-aux DOES. A knob's raw 0-to-1 position "
    "is not a readable parameter row -- the screen said og-knob-1 0.245 where a BPM "
    "belonged \\, and the param layer replaces the footer \\, so the tempo it was "
    "mapped to vanished while you turned it. u_map reports the value instead \\, "
    "because it is the only file that knows what a control MEANS. Item 242 \\, and "
    "until this gate existed it was written down in one #X text and nowhere else.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: organelle-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/organelle-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="ORG",
                      taps=["param", "disp", "err"], quit_ms=QUIT_MS,
                      blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
