#!/usr/bin/env python3
"""Generates the timed driver for the device-presence gate, into the scratch path.

⛔ THE WHOLE POINT IS WHAT IT DOES **NOT** SEND. This gate drives no device
inquiry reply at all -- [sysexin] has been rewritten to [t_sysexin] in the
scratch copy and nothing is ever pushed at it -- so the patch is running against
a Launchpad that was ABSENT AT LOAD and never answers. That is item 235's exact
condition, and it is the one case the watchdog was built unable to handle.

⚠️ SO THE SILENCE IS THE STIMULUS, WHICH MEANS IT NEEDS A LIVENESS WITNESS. A run
where the scratch copy failed to load at all also produces no replies, and every
"nothing happened yet" assertion below would pass on it. Two things stop that:
u_init's own boot wire.sh must appear in the BOOT window, and the grid must still
be painting at the end.

THE SCHEDULE IS THE WATCHDOG'S OWN ARITHMETIC, and none of it is free:

    3000 ms   u_init's launchpad stage raises $0-want -- [metro 2000] starts and
              fires immediately, so the ticks are 3000, 5000, 7000, ...
    7000 ms   the third missed poll. moses 3 sends right, loss is declared
    9000 ms   recovery tick 1        11000 ms  tick 2
   13000 ms   tick 4 -- mod 4 hits 0 and wire.sh is forked FOR THE FIRST TIME
   71000 ms   counter 33, the give-up

⛔ THE WINDOWS STRADDLE 7000 AND 13000 RATHER THAN SITTING AFTER THEM. A gate that
only looked at the end could not tell "fires on the fourth tick" from "fires on
every tick", and the interval is half of what the bound is made of. AFTER-LOSS
exists purely to be EMPTY.

⚠️ THE BOUND IS NOT ASSERTED HERE and this file must not grow to 71 seconds to do
it. It moves to u_present in Phase 4, which takes the tick and the settle as
creation arguments -- and a scratch copy can then scale them and reach the bound
in a few seconds without touching the counts.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 40

SEQ = [
    # u_init forks all four .sh scripts inside this window -- wire.sh at 1500 ms.
    # ⛔ IT IS THE LIVENESS WITNESS, not decoration: every other shell assertion
    # here is of the form "nothing forked", which an empty capture answers just
    # as well as a working patch does.
    (300, "BOOT", [], GAP),

    # Before the third missed poll. Nothing has been declared lost yet.
    (6000, "BEFORE-LOSS", [], GAP),

    # ⛔ AFTER THE LOSS AND BEFORE THE FOURTH TICK, AND IT EXISTS TO BE EMPTY.
    # Ticks 1 and 2 of the recovery counter land in here. A re-wire in this
    # window means the interval has gone and the bound is meaningless -- eight
    # attempts over 70 s becomes thirty-four over the same 70 s.
    (8000, "AFTER-LOSS", [], GAP),

    # The fourth tick lands at 13000, inside this window.
    (12000, "WAITING", [], GAP),

    # ⛔ AND THE INVARIANT THE ARMING GATE EXISTS FOR. A mode change dirties
    # g_grid, which paints only while it owns the surface -- so a frame arriving
    # here proves ownership was NOT dropped by a detector that has never once
    # seen a reply. Without that half, "arm the recovery at load" would look
    # identical to "delete the arming gate", which cost 7 of 24 checks once.
    (14000, "AFTER-REWIRE", ["\\; mode compose mode-3"], GAP),

    (15500, "OWNED", [], GAP),
]
QUIT_MS = 16500

BLURB = ("presence-assert-drive -- GENERATED by presence-assert-drive-gen.py. Do not "
         "edit this file. It drives NOTHING at the Launchpad: no device inquiry reply "
         "ever arrives \\, which is the absent-at-load case of item 235. What it "
         "asserts is that the bounded re-wire fires anyway \\, on the fourth tick and "
         "not the first \\, and that the grid is still owned when it does.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/presence-assert.sh \\, never by hand. The gate copies "
    "t_shell.pd over shell.pd inside a scratch copy so every wire.sh fork PRINTS \\, "
    "and rewrites [sysexin] to [t_sysexin] so the reply can be withheld deliberately "
    "rather than merely being absent. Run against the real Cut It nothing prints and "
    "every count below is answered by an empty list.",

    "⛔ ITEM 235 IN ONE LINE: the recovery used to sit behind a spigot armed by the "
    "device's own reply \\, so a device that was never there never armed it \\, never "
    "got re-wired \\, and could not even report that it had given up. The give-up path "
    "was downstream of the same shut spigot \\, which is why the error log was empty.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: presence-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/presence-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="PRES", taps=["err"],
                      quit_ms=QUIT_MS, blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
