#!/usr/bin/env python3
"""Generates the two timed drivers for the recover gate.

⛔ TWO RUNS, AND THE ONLY DIFFERENCE IS WHAT IS ON DISK. Run A boots with no
breadcrumb and drives the button: a tap must reach panic and nothing else, a
hold must reach recover as well. Run B boots with a breadcrumb ALREADY there,
which is the state the next boot after a real recover is in -- so it asserts the
arming override, the deferred report and the clear.

⛔ THE TAP AND THE HOLD ARE SEPARATE WINDOWS APART, NOT ONE INSTANT. A press and
a release fired in the same logical instant would prove that [del] can be
stopped and nothing about a THRESHOLD -- [del 0] still defers to the next
scheduler tick, so a zero-length press is not a short press. Both gestures here
are two real events seconds apart, and the tap's timer is given room to expire
in a window of its own so that a missing `stop` shows up as a recover nobody
asked for.

⚠️ THE WINDOW BOUNDARIES DODGE THREE COINCIDENCES, all of them deliberate. The
grid's modal-off lands exactly 1000 ms after each panic; u_init's fork lands 300
ms after recover; and the tap's cancelled timer would have expired 2000 ms after
its press. A window opening on any of those instants would make the assertion a
coin toss rather than a test.

⛔ THE WINDOWS ARE NOT DERIVED FROM THE IMPLEMENTATION. The hold is held for
longer than the threshold and the tap is far shorter, so both stay right if the
2000 ms is ever retuned; only TAP-EXPIRED knows the number, and it knows it in
the direction that makes the test STRICTER rather than vacuous.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 40

# ---------------------------------------------------------------- run A
# No breadcrumb on disk. Drive the button and watch the two tiers.
SEQ_A = [
    # Before anything is touched. Every "nothing happened" assertion needs a
    # window that provably ran, and this is also the one that proves a boot on
    # its own never reaches recover.
    (300, "EARLY", [], GAP),

    # THE TAP. Down, then up 300 ms later -- far short of the threshold.
    (5000, "TAP-DOWN", ["\\; param lp-cc-90 127"], GAP),
    (5300, "TAP-UP", ["\\; param lp-cc-90 0"], GAP),

    # ⛔ 6500 AND NOT 6000. The grid's modal-off lands at exactly 6000, 1000 ms
    # after the tap's panic, so a window opening there could take it either way.
    (6500, "AFTER-TAP", [], GAP),

    # ⛔ THE WINDOW THE WHOLE CANCEL RESTS ON. The tap pressed at 5000 armed a
    # 2000 ms timer that would fire at 7000, inside AFTER-TAP. If the release
    # did not stop it, a recover appears with nobody holding anything.
    (7500, "TAP-EXPIRED", [], GAP),

    # THE HOLD. Down at 9000, so the timer completes at 11000.
    (9000, "HOLD-DOWN", [], GAP),
    (9100, "HOLD-PRESS", ["\\; param lp-cc-90 127"], GAP),

    # Opened before the timer completes, so the recover cannot be read out of a
    # window that had already started.
    (10800, "HOLD-WAIT", [], GAP),

    # ⛔ 11800 AND NOT 11300. u_init waits 300 ms after panic before forking, so
    # the fork lands at 11300 exactly.
    (11800, "HOLD-FIRED", [], GAP),

    (12500, "HOLD-UP", ["\\; param lp-cc-90 0"], GAP),
    (13500, "DONE", [], GAP),
]
QUIT_A = 14200

# ---------------------------------------------------------------- run B
# A breadcrumb IS on disk, and so is a knobs.txt. This is the boot after a
# recover: nothing may be held, and the attempt must be reported once.
SEQ_B = [
    (300, "EARLY", [], GAP),

    # Stands in for mother replaying knobs.txt inside the 1000 ms boot window.
    # Without it nothing arms and the run would prove nothing either way --
    # a knob that was never held is not evidence that a knob was released.
    (400, "PUSH", ["\\; param og-knob-1 0.0957967"], GAP),

    # Opens after the 2000 ms probe and before the 4500 ms report, so the two
    # halves of one read land in windows of their own.
    (2500, "AFTER-PROBE", [], GAP),

    # ⛔ 5000 AND NOT 4500. The report is deferred to exactly 4500.
    (5000, "REPORTED", [], GAP),

    # The knob is moved well past the boot window. With the breadcrumb read it
    # must reach the tempo bus; held, it would reach nothing at all.
    (5500, "KNOB", ["\\; param og-knob-1 0.5"], GAP),

    (6500, "DONE", [], GAP),
]
QUIT_B = 7200

BLURB_A = ("recover-assert-drive -- GENERATED by recover-assert-drive-gen.py. Do not "
           "edit this file. Run A: no breadcrumb on disk \\, and the button is driven "
           "twice -- a tap that must reach panic and nothing else \\, then a hold that "
           "must reach recover as well.")

BLURB_B = ("recover-assert-drive -- GENERATED by recover-assert-drive-gen.py. Do not "
           "edit this file. Run B: a breadcrumb is ALREADY on disk \\, which is the "
           "state the next boot after a real recover is in. Nothing may be held \\, and "
           "the attempt must be reported once and then cleared.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/recover-assert.sh \\, never by hand. The gate copies a "
    "counting stub over shell.pd in its scratch copy \\, which is the only way to see "
    "that recover.sh was forked at all -- the real [shell] does not exist on a Mac and "
    "mac-stubs/shell.pd deliberately swallows the command.",

    "⛔ THIS GATE CANNOT ASSERT THAT THE RELOAD HAPPENED \\, and no future edit should "
    "imply that it can. [shell] is stubbed \\, so nothing is sent to mother and nothing "
    "is loaded. What it proves is that the right command was formed \\, in the right "
    "order \\, behind the silence -- and that the breadcrumb was on disk before the fork. "
    "The reload itself is a bench step and only a bench step.",

    "⛔ NOR CAN IT ASSERT THAT quitting STILL FIRES. quitting comes from mother.pd and "
    "u_mother-stub deliberately never sends it \\, so on the Mac neither receiver ever "
    "runs. What it CAN prove is the half that would break it: this path never touches "
    "m_launchpad's ownership \\, so the safe exit is still there to run. Item 251.",
]

if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit("usage: recover-assert-drive-gen.py OUT.pd a|b  "
                 "(run it through test/gate/recover-assert.sh)")
    which = sys.argv[2].lower()
    if which == "a":
        seq, quit_ms, blurb = SEQ_A, QUIT_A, BLURB_A
    elif which == "b":
        seq, quit_ms, blurb = SEQ_B, QUIT_B, BLURB_B
    else:
        sys.exit("recover-assert-drive-gen.py: run must be 'a' or 'b', got %r" % which)

    w, b, c = D.build(sys.argv[1], seq, tag="REC",
                      taps=["disp", "err", "tempo", "param"],
                      quit_ms=quit_ms, blurb=blurb, notes=NOTES)
    print("%s  run %s  %d windows  %d boxes  %d connects"
          % (sys.argv[1], which.upper(), w, b, c))
