#!/usr/bin/env python3
"""Generates the timed driver for the SP-404 gate, into the scratch path it is given.

⛔ THE ONLY DRIVER HERE THAT REACHES A RECEIVE PATH. Every output path in this
instrument can be driven from a bus; m_404's whole receive side sits behind
[notein] and NO BUS REACHES A MIDI INPUT. That is why the gate rewrites notein
to t_notein -- a stub that is [r t-notein] into [unpack f f f] -- and why this
driver sends bare `t-notein <pitch> <velocity> <channel>` messages.

⚠️ `t-notein` IS A BARE GLOBAL NAME OUTSIDE THE PROJECT'S ALLOWLIST, and that is
fine: it exists only inside the scratch copy, which is thrown away. Said here so
nobody 'fixes' it.

⛔ THE TWO EARLY WINDOWS ARE THE POINT OF THE SCHEDULE. Both directions are
exercised before u_map reads its table, because the gate this was split out of
started every window at 2400 ms for the reason the code was ready at 2000 -- and
a test whose schedule is derived from the implementation cannot falsify it.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 20

SEQ = [
    # ⛔ BEFORE u_map reads its table, both ways round.
    (300, "EARLY-TX", ["\\; param gk-p1 100"], GAP),
    # ⚠️ 700, not 400. The pad above sends its note-off 200 ms behind its note-on,
    # and a window opened at 400 would count that off against itself.
    (700, "EARLY-RX", ["\\; t-notein 48 77 33"], GAP),
    # all sixteen pads of bank A, spaced well clear of the 5 ms limiter.
    # ⚠️ The next window must leave room for the LAST note-off, 200 ms behind
    # the last note-on, or it is counted against the wrong window.
    (2900, "PADS-A", ["\\; param gk-p%d 100" % n for n in range(1, 17)], GAP),
    (3600, "PADS-C", ["\\; param gk-pc1 100"], GAP),
    (4000, "RX-B5", ["\\; t-notein 44 90 34"], GAP),
    (4100, "RX-RELEASE", ["\\; t-notein 44 0 34"], GAP),
    (4200, "RX-A1", ["\\; t-notein 48 77 33"], GAP),
    (4300, "RX-REJECT", ["\\; t-notein 44 90 20"], GAP),
    # ⛔ TWO TRIGGERS 2 ms APART -- the ONLY window that can see a DISARMED limiter.
    # The BURST cannot: [del 0] still defers to the next scheduler tick, so inside
    # one logical instant the gate never reopens whatever the interval is, and a
    # disarmed limiter passes that test. This one straddles the 5 ms gate.
    (4800, "PAIR", ["\\; param gk-p1 100", "\\; param gk-p2 100"], 2),
    (5400, "PANIC", ["\\; panic bang"], GAP),
]
BURST = (4600, 20, "\\; param gk-p1 100")
QUIT_MS = 6000

BLURB = ("sp404-assert-drive -- GENERATED by sp404-assert-drive-gen.py. Do not edit "
         "this file. It drives m_404 in BOTH directions: all sixteen pads of bank A \\, "
         "a second bank \\, the rate limiter from two sides \\, four incoming pad events "
         "including one on a channel the 404 does not own \\, and panic.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/sp404-assert.sh \\, never by hand. The gate rewrites "
    "noteout \\, ctlout and notein to printing stubs in a SCRATCH COPY and appends its "
    "own mapping rows. Loaded on its own against the real patch it would emit real MIDI "
    "to whatever is plugged in \\, and nothing would drive the receive side at all.",

    "⚠️ THE STATE DIRECTORY IS THE GATE'S OWN AND MUST BE EMPTY. main-dev.pd passes "
    "/tmp \\, which every run on the machine shares -- and u_init restores saved state at "
    "about 3.5 s. A previous test that changed mode leaves mode in that file \\, the "
    "restore republishes it mid-run \\, and every row keyed to another mode stops matching "
    "from that instant. It cost a wrong diagnosis once already: item 232.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: sp404-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/sp404-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="SP404",
                      taps=["param", "disp", "err"], quit_ms=QUIT_MS,
                      blurb=BLURB, burst=BURST, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
