#!/usr/bin/env python3
"""Generates the timed driver for the tempo gate, into the scratch path given.

⚠️ EVERY WINDOW HERE IS A MEASUREMENT, not a single event, which makes this the
one driver whose window LENGTHS matter as much as their start times. The
assertions count System Real-Time bytes over a known span, so a window that is
moved or shortened changes the number it is checked against.

⛔ THE RATE WINDOWS START AT 4000 ms ON PURPOSE, and not for the usual reason.
Everywhere else in this suite an early window is the point; here the opposite is
true. u_init restores saved state at about 3.5 s and republishes what it finds,
so a counting window straddling that instant could have its tempo changed
underneath it mid-count. The transport and clamp windows -- which assert on
events rather than on a rate -- are unaffected and stay where they are.

⚠️ DSP GOES ON AT 300 ms AND STAYS ON. The clock is built in the audio domain:
BPM / 60 * 24 into a [phasor~], then [threshold~ 0.5 0 0.1 0] for one bang per
cycle. Under -noaudio the phasor never advances and every count here is zero,
which reads exactly like a dead clock rather than a missing flag.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 20

# The nominal pulse rate is BPM / 60 * 24 Hz -- 48 Hz at 120 BPM, so a two-second
# window holds 96 pulses PER PORT. The analyser recomputes these rather than
# trusting the numbers in this comment.
SEQ = [
    (300, "DSP-ON", ["\\; pd dsp 1"], GAP),

    # --- rate: two windows an octave apart -------------------------------
    (4000, "RATE-120", [], GAP),                 # 4000..6000, 2 s at 120 BPM
    (6000, "SET-60", ["\\; tempo 60"], GAP),
    (6200, "RATE-60", [], GAP),                  # 6200..8200, 2 s at 60 BPM
    (8200, "SET-120", ["\\; tempo 120"], GAP),

    # --- the clamp, proven on the WIRE rather than on the bus -------------
    # ⛔ An in-range tempo must NOT warn. [change] sits on the VALUE, not on the
    # verdict, so this is the case that would break if anyone "fixed" that:
    # filtering the flag instead would make a 500 warn and a following 5 silent.
    (8400, "IN-RANGE", [], GAP),
    # 5000 is clamped to 600 BPM = 240 Hz. A one-second window separates 240 from
    # 2000 beyond any argument about tolerance.
    (9000, "TOO-HIGH", ["\\; tempo 5000"], GAP),
    (10000, "TOO-LOW", ["\\; tempo 0"], GAP),
    (11000, "BACK", ["\\; tempo 120"], GAP),

    # --- the transport ----------------------------------------------------
    (12000, "START", ["\\; start bang"], GAP),
    (13000, "STOP", ["\\; stop bang"], GAP),
    # ⛔ 1.5 s AFTER the stop. This is the window that proves stop does not halt
    # the clock -- a running phasor nobody reads is silent, and halting it is the
    # consumer's business.
    (13500, "AFTER-STOP", [], GAP),
    (15000, "PANIC", ["\\; panic bang"], GAP),
]
QUIT_MS = 16000

BLURB = ("tempo-assert-drive -- GENERATED by tempo-assert-drive-gen.py. Do not edit "
         "this file. It drives u_tempo: the pulse rate at two tempos \\, the clamp at "
         "both ends and its warning \\, the three transport bytes \\, and the fact that "
         "a stop does not halt the clock.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/tempo-assert.sh \\, never by hand -- the whole point is "
    "that [midiout] has been rewritten to [t_midiout] in a scratch copy first \\, so "
    "every System Real-Time byte reaches stdout instead of a cable.",

    "⛔ DSP MUST BE ON. u_tempo's pulse is a [phasor~] read by [threshold~] \\, so it "
    "lives in the audio domain and a silent run counts zero pulses at every tempo. That "
    "is why this gate costs about sixteen seconds where the MIDI gates cost seven.",

    "⚠️ THE CLOCK GOES OUT ON TWO PORTS -- 1 for the Launchpad \\, which paces its flash "
    "and pulse animations from incoming clock \\, and 3 for the SP-404 \\, whose BPM SYNC "
    "learns tempo ONLY by measuring pulse intervals. Both are counted separately here \\, "
    "because a fan-out that quietly lost one port would look perfect on the other.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: tempo-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/tempo-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="CLK",
                      taps=["err"], quit_ms=QUIT_MS, blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
