#!/usr/bin/env python3
"""Generates the timed driver for the Volca gate, into the scratch path it is given.

Three destinations, one device, and the only one of the three that is not
obvious: pgmout. ⛔ Pd's [pgmout] is 1-BASED on its inlet and the wire is
0-based, so m_volca adds one and the number on the wire is the number asked for.
Item 228.

⛔ THE EARLY WINDOW IS DELIBERATE AND IT IS NOT ABOUT THE VOLCA. It fires the CC
at 300 ms, before u_map reads its table, because the gate this was split out of
timed every window from when the implementation happened to be ready and
therefore could not falsify it. Item 234 was found by hardware, not by that gate.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_drive as D                                          # noqa: E402

GAP = 20

SEQ = [
    (300, "EARLY", ["\\; param gk-cc 64"], GAP),
    (2600, "VOLCA-CC", ["\\; param gk-cc 64"], GAP),
    (2700, "VOLCA-NOTE", ["\\; param gk-note 100"], GAP),
    (2800, "VOLCA-PROG", ["\\; param gk-prog 100"], GAP),

    # --- ⛔ volca-key: A REAL NOTE-ON AND A REAL NOTE-OFF -------------------
    # volca-note cannot be a keyboard: its arg is the PITCH, and its duration is
    # a fixed 200 ms, so a held key would release itself. This pair is the whole
    # difference -- the note-off comes from the KEY, as velocity 0.
    (2900, "VOLCA-KEY-ON", ["\\; param gk-key 100"], GAP),
    # ⛔ THE HELD WINDOW IS THE ONE THAT DISCRIMINATES, and it took a mutation to
    # find that out. Both a real key path and a makenote path put a note-on and
    # then a note-off on the wire, so nothing about the two messages tells you
    # WHO produced the off -- the first version of this gate asserted exactly
    # that and passed with makenote spliced in. What a keyboard must do is
    # NOTHING while the key is down: this window opens 400 ms after the press,
    # twice volca-note's fixed 200 ms duration, and sends no action at all.
    (3050, "VOLCA-KEY-HELD", [], GAP),
    (3500, "VOLCA-KEY-OFF", ["\\; param gk-key 0"], GAP),

    # --- ⛔ PANIC, WHICH THIS DEVICE HAD NO NEED OF UNTIL NOW ---------------
    # makenote always scheduled its own note-off, so nothing here could leave a
    # note sounding. The key path bypasses makenote deliberately, so the risk
    # comes back and All Notes Off ships in the same breath.
    (3800, "VOLCA-PANIC", ["\\; panic 1"], GAP),
]
QUIT_MS = 4800

BLURB = ("volca-assert-drive -- GENERATED by volca-assert-drive-gen.py. Do not edit "
         "this file. It drives m_volca through the map: a control change \\, a note \\, "
         "and a program change \\, each on the Volca's own channel.")

NOTES = [
    "⚠️ RUN IT THROUGH test/gate/volca-assert.sh \\, never by hand. The gate rewrites "
    "noteout \\, ctlout and pgmout to printing stubs in a SCRATCH COPY and appends its "
    "own mapping rows. Loaded on its own against the real patch it would emit real MIDI "
    "to whatever is plugged in.",
]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: volca-assert-drive-gen.py OUT.pd  "
                 "(run it through test/gate/volca-assert.sh, which passes a scratch path)")
    w, b, c = D.build(sys.argv[1], SEQ, tag="VOLCA",
                      taps=["param", "err"], quit_ms=QUIT_MS,
                      blurb=BLURB, notes=NOTES)
    print("%s  %d windows  %d boxes  %d connects" % (sys.argv[1], w, b, c))
