"""Step tables for the four benches -- the DATA half of bench-gen.py.

phase3/4/5 were transcribed out of the hand-authored .pd files by
tools/bench-extract.py and must not be reworded: those benches are verified on
the Organelle and the conversion to manual stepping is meant to change how a
step is DRIVEN, never what it claims. tools/bench-verify.sh re-extracts from the
regenerated files and diffs against these tables.

Each step is (title, pass_if, [(message, bus), ...]).

ONE DELIBERATE TEXT CHANGE, and it is a bug fix rather than a reword. phase5's aux
step carried two escaped commas inside its PASS IF. `\\,` satisfies the .pd PARSER,
but a message box still treats the comma atom as a message separator -- measured
again here -- so at runtime that line printed as THREE fragments. Both are now
` -- `. This is the same defect that produced fourteen fragments on the first
Phase 6 run, in a bench family whose own README warns about it, which is why
bench-gen.py asserts against commas and semicolons rather than trusting review.
"""

STEPS3 = [
 ('baseline -- sending nothing',
  'PASS IF: two bars with a small gate mark under each and a BPM at the bottom -- Phase 5 hands the footer over from v0.2-ready to the tempo about four seconds in',
  []),
 ('PARAM WITH A UNIT -- sending chop-size 43 %',
  'PASS IF: chop-size on the top line and a big 43 % under it -- bars shrink to a thin strip -- then about 1.2s later the meters come back on their own',
  [('chop-size 43 %', 'disp')]),
 ('PARAM WITH NO UNIT -- sending grain 12',
  'PASS IF: grain then a big 12 and NO PERCENT SIGN left over from the last step -- this is the one that matters most',
  [('grain 12', 'disp')]),
 ('MODAL -- sending modal recording',
  'PASS IF: recording in mid-size text with the bars as a thin strip -- and unlike a param it STAYS and does not fade',
  [('modal recording', 'disp')]),
 ('PARAM WHILE A MODAL IS UP -- sending chop-size 43 %',
  'PASS IF: NOTHING CHANGES -- still says recording and chop-size never appears -- the modal outranks it',
  [('modal recording', 'disp'), ('chop-size 43 %', 'disp')]),
 ('WARNING OVER THE MODAL -- sending warn u_root test-warn',
  'PASS IF: a box border with warn then u_root then test-warn -- AND about 2s later it vanishes and RECORDING IS BACK underneath',
  [('modal recording', 'disp'), ('warn u_root test-warn', 'err')]),
 ('MODE TO PERFORM -- nothing is sent to the screen',
  'PASS IF: NOTHING CHANGES -- still recording. Mode is never drawn -- this only sets up the next two steps',
  [('modal recording', 'disp'), ('perform', 'mode')]),
 ('WARNING WHILE IN PERFORM -- sending warn u_root hidden-warn',
  'PASS IF: NOTHING CHANGES -- no alert box at all -- still recording. Perform mode suppresses warnings',
  [('modal recording', 'disp'), ('warn u_root hidden-warn', 'err')]),
 ('FAILURE WHILE IN PERFORM -- sending fail u_root shown-fail',
  'PASS IF: an alert DOES appear -- fail then u_root then shown-fail -- failures are never suppressed -- then recording returns after about 4s',
  [('modal recording', 'disp'), ('fail u_root shown-fail', 'err')]),
 ('MODE BACK TO COMPOSE -- nothing is sent to the screen',
  'PASS IF: NOTHING CHANGES -- still recording',
  [('modal recording', 'disp'), ('compose', 'mode')]),
 ('WARNING NOW WE ARE BACK IN COMPOSE -- sending warn u_root back-again',
  'PASS IF: the alert DOES appear this time -- warn then u_root then back-again -- the filter released',
  [('modal recording', 'disp'), ('warn u_root back-again', 'err')]),
 ('CLEARING THE MODAL -- sending modal-off',
  'PASS IF: recording disappears and you are back to the two meters and the BPM footer',
  [('modal-off', 'disp')]),
 ('SAFETY TIMEOUT -- sending modal stuck and then DELIBERATELY never clearing it',
  'PASS IF: stuck appears now -- then with NO further input it clears itself after 30s. Next line is in 35s',
  [('modal stuck', 'disp')]),
 ('done -- press Ctrl-C',
  'PASS IF: the screen returned to the meters on its own during that 35s wait -- that was the safety timeout',
  []),
]

STEPS4 = [
 ('baseline -- sending nothing',
  'PASS IF: two bars with a small gate mark under each and a BPM at the bottom -- Phase 5 hands the footer over from v0.2-ready to the tempo about four seconds in',
  []),
 ('ONE MOVER -- chop-size 43 %',
  'PASS IF: chop-size small on the top line and a BIG 43 % under it -- this is the Phase 3 layout and it must be unchanged',
  [('chop-size 43 %', 'disp')]),
 ('TWO MOVERS -- chop-size and grain together',
  'PASS IF: TWO stacked pairs -- chop-size over 43 % on top and grain over 12 below -- FIRST TOUCHED on top and the value mid-sized',
  [('chop-size 43 %', 'disp'), ('grain 12', 'disp')]),
 ('FIVE MOVERS',
  'PASS IF: FIVE small lines in the order they were first touched: chop-size then grain then slider-1 then knob-3 then btn-t-2',
  [('chop-size 43 %', 'disp'), ('grain 12', 'disp'), ('slider-1 64', 'disp'), ('knob-3 100', 'disp'), ('btn-t-2 1', 'disp')]),
 ('SEVEN MOVERS -- two more than fit',
  'PASS IF: still exactly FIVE lines -- a1 a2 a3 a4 a5 -- and a6 and a7 are REFUSED rather than pushing the rows around. Nothing shifts',
  [('a1 1', 'disp'), ('a2 2', 'disp'), ('a3 3', 'disp'), ('a4 4', 'disp'), ('a5 5', 'disp'), ('a6 6', 'disp'), ('a7 7', 'disp')]),
 ('AGEING -- only a1 is kept alive from here',
  'PASS IF: the other four fade out within about 1.3 s and a1 alone is left -- and it grows BACK to the big 24px layout',
  [('a1 1', 'disp')]),
 ('MODAL OVER PARAMETERS -- modal recording',
  'PASS IF: recording at mid size and NO parameters at all -- the modal outranks them',
  [('modal recording', 'disp'), ('chop-size 43 %', 'disp')]),
 ('WARNING OVER THE MODAL',
  'PASS IF: a bordered alert -- warn then u_root then bench-warn -- then about 2 s later it vanishes and RECORDING IS STILL THERE underneath',
  [('modal recording', 'disp'), ('warn u_root bench-warn', 'err')]),
 ('PERFORM MODE -- nothing is drawn',
  'PASS IF: NOTHING CHANGES -- still recording. This only sets up the next two steps',
  [('modal recording', 'disp'), ('perform', 'mode')]),
 ('WARNING WHILE IN PERFORM',
  'PASS IF: NOTHING CHANGES -- no alert at all. Perform suppresses warnings',
  [('modal recording', 'disp'), ('warn u_root hidden-warn', 'err')]),
 ('FAILURE WHILE IN PERFORM',
  'PASS IF: an alert DOES appear -- failures are never suppressed -- then recording returns after about 4 s',
  [('modal recording', 'disp'), ('fail u_root shown-fail', 'err')]),
 ('BACK TO COMPOSE',
  'PASS IF: NOTHING CHANGES -- still recording',
  [('modal recording', 'disp'), ('compose', 'mode')]),
 ('WARNING NOW WE ARE IN COMPOSE',
  'PASS IF: the alert DOES appear this time -- the filter released',
  [('modal recording', 'disp'), ('warn u_root back-again', 'err')]),
 ('CLEARING THE MODAL',
  'PASS IF: recording disappears and you are back to the two meters and the BPM footer',
  [('modal-off', 'disp')]),
 ('THE NANO -- sweep every slider and knob now',
  "PASS IF: each control names ITSELF -- slider-1 to slider-9 then knob-1 to knob-9 -- and none reports another's name. Watch slider 9 then knob 1 especially: CC 9 and CC 11 are where an off-by-one shows",
  []),
 ('THE NANO -- two faders at once then three then all nine',
  'PASS IF: two stay readable as stacked pairs -- three to five become small lines -- and nine shows the FIVE YOU TOUCHED FIRST with the rest refused. Rows must not reshuffle while you move things',
  []),
 ('THE NANO -- press every button then all six transport keys',
  'PASS IF: all 18 buttons name themselves on press and nothing on release. The six transport keys report xport-1 to xport-6 on press -- no toggle and no footer change',
  []),
 ('done -- press Ctrl-C',
  'PASS IF: every step above was marked off. If step 2 or 6 failed the display work regressed. If 15 to 17 failed m_nano did',
  []),
]

STEPS5 = [
 ('baseline -- re-asserting 120 BPM and stopped',
  'PASS IF: two bars with a small gate mark under each and 120-bpm in the footer -- and the aux button lit DARK BLUE. This step exists so the run repeats without reopening the patch',
  [('120', 'tempo'), ('bang', 'stop')]),
 ('COUNTING -- zeroing the beat counters for 10 s at 120 BPM',
  'PASS IF: NOTHING VISIBLE CHANGES. The transport is still stopped and the clock is running anyway -- which is exactly what is being counted',
  [('bang', '\\$0-zero')]),
 ('READ THE COUNTS -- the clock ran for 10 s while STOPPED',
  'PASS IF: M-BEATS 20 or 21 -- C1-BEATS the same number -- C2-BEATS 30 or 31. A zero anywhere means the clock does not run until the transport does -- or on the Mac it means DSP is off which looks exactly the same',
  [('bang', '\\$0-read')]),
 ('START THE TRANSPORT',
  "PASS IF: the aux button turns GREEN and the 404 starts its pattern. WATCH EXT ON THE 404'S PATTERN SELECT SCREEN -- the number beside a pad is that SAMPLE's BPM and never moves",
  [('bang', 'start')]),
 ('TEMPO THROUGH THE MAP -- og-knob-1 at 0',
  "PASS IF: the footer reads 10-bpm and the 404's EXT number slides down to meet it within a second or two. THIS IS THE REAL done-when",
  [('og-knob-1 0', 'param')]),
 ('TEMPO THROUGH THE MAP -- og-knob-1 at 1',
  "PASS IF: the footer reads 500-bpm and the 404's EXT slides up again. A slide rather than a snap IS the inference working -- it snaps only to a tempo it has already learned",
  [('og-knob-1 1', 'param')]),
 ('OUT OF RANGE -- 5000 sent TWICE',
  'PASS IF: the footer reads 600-bpm and EXACTLY ONE alert appears -- a bordered box naming u_tempo. The second 5000 must be silent because the VALUE did not change',
  [('5000', 'tempo'), ('5000', 'tempo')]),
 ('OUT OF RANGE THE OTHER WAY -- 0',
  'PASS IF: the footer reads 5-bpm and a SECOND alert appears. The verdict did not change but the value did -- and this is the case that was broken once',
  [('0', 'tempo')]),
 ('BACK TO 120',
  'PASS IF: the footer reads 120-bpm and NO alert appears at all',
  [('120', 'tempo')]),
 ('STOP -- and the clock must NOT stop with it',
  'PASS IF: the aux button goes DARK BLUE and the 404 stops -- but its display MUST STILL SAY EXT. If it falls back to BPM the clock stopped with the transport and that is the bug this step exists for',
  [('bang', '\\$0-zero'), ('bang', 'stop')]),
 ('READ THE COUNTS WHILE STOPPED',
  'PASS IF: M-BEATS 20 or 21 again. Stop the pulse stream and the 404 stretches every sample to a stale tempo -- so this is the least obvious requirement in the phase',
  [('bang', '\\$0-read')]),
 ('PANIC',
  'PASS IF: the aux button turns RED and the footer says panic -- and the clock is STILL running underneath',
  [('bang', 'panic')]),
 ('BY HAND -- press the aux button twice',
  'PASS IF: ON THE DEVICE use the real button. ON THE MAC use aux-tap and NOT the aux toggle -- aux is momentary 1 then 0 and only the 1 is a press -- so a toggle needs two clicks per press and the uncheck is meant to do nothing. First press GREEN and the 404 starts -- second DARK BLUE and it stops. If nothing happens at all then mother is eating the press',
  []),
 ('BY HAND -- sweep KNOB 1 all the way and back',
  'PASS IF: og-knob-1 appears as a parameter row on the OLED and the footer tracks between 10-bpm and 500-bpm. The 404 follows the sweep',
  []),
 ('done -- press Ctrl-C',
  'PASS IF: every step above was marked off. If 2 3 10 or 11 failed the clock is wrong -- if 5 6 or 14 failed the map is -- if 4 12 or 13 failed the transport or the LED is',
  []),
]

STEPS6 = [
 ('baseline -- 120 BPM -- stopped -- compose mode-1',
  'PASS IF: the top row shows ONE bright green lamp at the far left and five dim ones beside it -- and the BOTTOM row of pads has a single white pad. DIM MEANS FAINT AND NOT OFF: the five idle lamps are colour 1 which is a near-black grey and the current one is 21. THE WHITE PAD IS ALREADY WALKING and that is correct -- c_clock free-runs and the transport gates what PLAYS rather than what counts -- so a frozen pad here is the fault and a moving one is not. Everything else on the surface is dark',
  [('120', 'tempo'), ('bang', 'stop'), ('compose mode-1', 'mode')]),
 ('MODE -- selecting the fourth mode',
  'PASS IF: the bright lamp MOVES to the fourth position and the other five go dim. Nothing else on the grid changes',
  [('perform mode-4', 'mode')]),
 ('MODE -- the second lamp',
  'PASS IF: the bright lamp lands on the SECOND position. Between this step and the next four the bus drives all six lamps in turn -- until now only two of the six were ever exercised without hands',
  [('compose mode-2', 'mode')]),
 ('MODE -- the fifth lamp',
  'PASS IF: the bright lamp lands on the FIFTH position and the other five go dim',
  [('perform mode-5', 'mode')]),
 ('MODE -- the sixth and last lamp',
  'PASS IF: the bright lamp lands on the sixth and last position. ONE MESSAGE PER STEP FOR ANYTHING VISUAL: two sent back to back both land inside the same frame and only the second is ever drawn -- found by running this bench and watching the painted frames rather than the surface',
  [('perform mode-6', 'mode')]),
 ('THE grid SELECTOR MUST NOT REACH THE OLED -- sending grid vocabulary g_grid ignores',
  'PASS IF: NOTHING HAPPENS ON EITHER SURFACE. g_oled treats every selector it does not recognise as a parameter to draw -- so without grid in its route this would appear on the OLED as a nonsense parameter row called grid. That one route argument is the whole reason a third display surface was cheap',
  [('grid no-such-thing', 'disp')]),
 ('MODAL -- the whole surface claimed',
  'PASS IF: EVERY pad and every lamp on the top row turns blue. The mode lamps are covered too -- that is the point of a modal. THE OLED MUST NOT CHANGE',
  [('grid modal 45', 'disp')]),
 ('MODE CHANGE UNDERNEATH A MODAL -- nothing should be visible',
  'PASS IF: NOTHING HAPPENS. The surface stays blue. The mode really does change underneath and you will see it two steps from now. THIS STEP RE-SENDS THE MODAL BEFORE THE MODE CHANGE and so does the next one -- not decoration: the modal safety TTL is thirty seconds of WALL CLOCK and under manual stepping the gap between two steps is however long you take. Without the re-send this chain silently expires mid-test and the surface is back to mode lamps before the step that needs it runs. Re-asserting a live modal is what a caller would do anyway and it restarts the timer',
  [('grid modal 45', 'disp'), ('perform mode-3', 'mode')]),
 ('ALERT ON TOP OF A MODAL -- two layers deep',
  'PASS IF: the surface turns RED for about two seconds and then goes back to BLUE -- NOT to the mode lamps. The modal is still up underneath and the alert only borrowed the surface. This is the only step that tests the cascade more than one layer deep. The modal is re-sent first for the same reason as the last step',
  [('grid modal 45', 'disp'), ('fail u_bench stacked', 'err')]),
 ('MODAL OFF',
  'PASS IF: the grid returns to mode lamps and the beat row -- and the bright lamp is now the THIRD one -- which is the change made while the modal covered it. THIS STEP RE-SENDS THE MODAL BEFORE CLEARING IT and that is not pointless: the 30 second safety TTL is wall clock and it has expired underneath this step before -- on the first device run -- because a report was being typed between the last step and this one. When that happens the surface has ALREADY returned home by itself and modal-off clears nothing -- the step passes while proving nothing at all. Raising it again first means there is always a modal here to clear. You will not SEE the re-raise because both messages land in one frame and only the last is drawn -- that is expected and it is why the previous steps carry the visible part of this test',
  [('grid modal 45', 'disp'), ('grid modal-off', 'disp')]),
 ('ALERT -- a fail -- which outranks everything',
  'PASS IF: the whole surface turns RED -- and then goes back to the mode lamps BY ITSELF after about two seconds. A grid that stays red is the bug this step exists for',
  [('fail u_bench boom', 'err')]),
 ('ALERT -- a warn -- which the grid must ignore but the OLED must show',
  'PASS IF: NOTHING HAPPENS ON THE GRID and the OLED DOES show the warning. Only a fail is worth the whole surface. THE compose SENT FIRST IS LOAD-BEARING and not a mode test: u_err gates warns off the SCREEN in perform mode -- compose sets its verbose spigot to 1 and perform sets it to 0 -- and this bench put itself in perform at step 8. Without the compose the OLED stays blank for a legitimate reason and the step cannot tell that apart from the grid filter working. Fails ignore the spigot which is why the previous step needed no such thing',
  [('compose mode-3', 'mode'), ('warn u_bench quiet', 'err')]),
 ('THE 30 SECOND MODAL SAFETY TTL -- this step needs you to wait',
  'PASS IF: the surface turns green and then clears ITSELF about thirty seconds later with nothing sent to it. DO NOT PRESS GO -- sit and watch it. A modal is sticky by design so this timer is the only thing between a stuck modal and a grid that never comes back. It has never once been observed',
  [('grid modal 21', 'disp')]),
 ('TRANSPORT -- start -- and the beat counter starts with it',
  'PASS IF: the white pad WALKS along the bottom row -- twice a second -- and the aux LED goes green. ON THE MAC THE AUX LED IS NOT A BUTTON: it is the numeric readout labelled aux-LED on the bottom row of the dev panel next to the clock beat bng and the tempo-bus box -- with a symbol box beside it spelling the colour. Only the Organelle has a lamp to look at. On the Mac with DSP off the pad will not move -- tick enable-DSP first. A BEATS line prints about ten seconds from now',
  [('bang', 'start'), ('bang', '\\$0-zero')]),
 ('THE BEAT ROW WRAPPING -- WATCH ONLY -- this step sends nothing on purpose',
  'PASS IF: the white pad reaches the EIGHTH pad and the next step is back to the FIRST -- with no gap and no stray light anywhere else. NO ACTION IS SENT AND THAT IS DELIBERATE rather than an omission: the wrap happens on the clock schedule and cannot be provoked on demand -- the only way to test it is to watch one go by -- and it gets its own step because folding it into the transport step is how it goes unlooked-at. Nothing here disturbs the ten second BEATS window still running underneath. THE BEAT NUMBER IS ONE-BASED: built against a zero-based assumption beat 8 landed on a right-column ring button and blanked the row once a bar -- and seven beats out of eight looked perfect',
  []),
 ('TEMPO -- 240 BPM -- so the beat row should double',
  'PASS IF: the white pad moves twice as fast. The BEATS line just printed covers ten seconds at 120 and should read about 20 -- the next one covers ten seconds at 240 and should read about 40. EXPECT A VISIBLE SWING HERE AND DO NOT FAIL THE STEP FOR IT. g_grid repaints on a metro 100 so the row can only move on a 100 ms boundary. At 120 BPM a beat is 500 ms which divides exactly and the walk is dead even. At 240 a beat is 250 ms which does not -- so beats land alternately at 200 and 300 ms and the row swings by 50 either way. The CLOCK is not swinging and the BEATS count is unaffected: this is the display quantising. It is the price of the 10 Hz repaint that keeps MIDI writes inside the CPU budget',
  [('bang', '\\$0-read'), ('240', 'tempo'), ('bang', '\\$0-zero')]),
 ('back to 120 and stopped',
  'PASS IF: the second BEATS line reads about 40 -- then the beat row slows to two a second. THE CLOCK KEEPS RUNNING WHEN THE TRANSPORT STOPS -- so the pad must keep walking after the stop',
  [('bang', '\\$0-read'), ('120', 'tempo'), ('bang', 'stop')]),
 ('HANDS ON THE LAUNCHPAD -- press pads and RELEASE them',
  'PASS IF: every pad you press reports pad-NN on the OLED with its velocity -- and RELEASING it reports the same name with 0. Bottom left is 11 and top right is 88. Pressure on a held pad reports NOTHING on the OLED -- that is deliberate and it is not a fault',
  []),
 ('HANDS ON THE LAUNCHPAD RING -- and the row that must stay dark',
  'PASS IF: the ring buttons report lp-cc-NN. Check the two the documentation got wrong: the TOP LEFT CORNER is 90 and the bottom row is 101 to 108. THEN LOOK AT CC 1 TO 8 -- AND NOTE THAT THIS EXPECTATION IS NOW THE OPPOSITE OF WHAT IT ONCE WAS. That row used to be outside the painted span and had to be DARK. It is INSIDE it now -- the span runs 1 to 108 -- so it must be lit like everything else and must go blue under a modal and red under an alert. THE REASON WAS NOT THAT ANYTHING WANTED THOSE EIGHT BUTTONS. LED state survives the Programmer Mode switch -- so an index outside the span keeps whatever Live Mode last drew there forever and no repaint can reach it. This bench is what caught that: the row was green from an old probe on one run and dark on the next -- with nothing in Cut It touching it either time. ONE BUTTON IS STILL OUTSIDE -- INDEX 0 -- SETUP -- and that one is measured rather than chosen: it takes no colour and it transmits nothing in Programmer Mode',
  []),
 ('HANDS ON THE NANOKONTROL -- the six transport keys',
  'PASS IF: each of the six keys moves the bright lamp to its own position. This is the mode bus finally having a driver',
  []),
 ('HANDS -- THE REPLUG HAZARD -- unplug the Launchpad and plug it back in',
  'PASS IF: RECORD WHAT HAPPENS -- this step documents a known hazard rather than asserting a fix. The device returns in Live Mode but m_launchpad still believes it owns the surface -- so press a few pads afterwards and watch the OLED: pad-NN names are the hazard showing itself because a stock layout sends musical pitches that get decoded as r*10+c. THIS STEP MUST COME BEFORE THE PANIC AND THAT IS THE WHOLE POINT. The hazard IS stale ownership -- run it after the panic and ownership has already been dropped legitimately so there is nothing stale left and the step silently tests nothing. It was ordered that way on the first run and proved exactly that. MEASURED SINCE: Pd does NOT lose the device on the Mac and the Launchpad still answers a universal device inquiry after a replug -- so this IS detectable by polling and the fix is unblocked. Not built yet. See plan-v02.md',
  []),
 ('PANIC -- the surface goes back to the device',
  'PASS IF: BUTTON PRESSES STOP REACHING THE OLED. That is the assertion -- not the Launchpad changing appearance -- because the step before this one already left it in Live Mode by unplugging it. Watch for the INPUT going quiet rather than the display changing. What just happened is the panic curing the hazard the replug created: ownership was still 1 over a device we no longer control -- so presses were being decoded as grid coordinates -- and the panic drops it. If the previous step was skipped the device WILL visibly leave Programmer Mode here and its own display will return. KNOWN AND DELIBERATE: it stays that way until the patch is reloaded -- so EVERY REMAINING STEP IS DOWNSTREAM OF THIS ONE and nothing after it can check the grid. If you have any doubt about an earlier step go back and redo it before pressing GO here',
  [('bang', 'panic')]),
 ('AFTER THE PANIC THE GRID MUST GO SILENT -- sending it a mode change',
  'PASS IF: NOTHING HAPPENS. The Launchpad keeps showing its own display and g_grid paints nothing at all. Ownership dropped when the surface was handed back -- so the arbiter still runs and simply never reaches the wire',
  [('compose mode-1', 'mode')]),
 ('HANDS -- press a pad now -- after the panic',
  'PASS IF: NOTHING REACHES THE OLED. In a stock layout the notes are musical pitches rather than r*10+c -- and decoding them as coordinates would publish nonsense. Reload the patch to get the grid back',
  []),
 ('END MARKER -- not a test -- the run is over',
  'PASS IF: nothing further prints. THIS STEP ASSERTS NOTHING and exists only so the last real step has something to advance INTO -- without it the final GO would fall off the end with no acknowledgement that the run finished rather than stalled. Reload with deploy.sh to restore normal operation',
  []),
]

