#!/usr/bin/env python3
"""Generates tools/state-assert-drive.pd -- the driver for the data store's gate.

WHY THIS GATE IS THE CHEAPEST IN THE SUITE. The MIDI gates rewrite object boxes in
a scratch copy of the patch, because a built-in class has no side channel.
phone-assert points u_net at 127.0.0.1 and reads real datagrams. u_state writes a FILE, so
this gate needs no scratch copy, no socket and no hardware -- it reads what
landed on disk. "Cut It/" is never touched.

TWO SYNTHETIC CONTRIBUTORS, AND THE SECOND ONE IS THE POINT. u_state's contract
is that a `manual` answer must be SYNCHRONOUS -- Pd is depth-first, so by the
time the save broadcast returns, every honest answer is already stored. That is
invisible and a contributor can break it by accident. So one contributor here
answers immediately and one answers from behind a [del 5], and the gate asserts
that the late one is ABSENT from the file. A rule nothing tests is a rule that
quietly stops being true.

Every delay hangs off ONE loadbang with an ABSOLUTE time. Chaining them would
make each wait the SUM of everything before it -- the arithmetic that silently
drifts as steps are added (phase7's driver makes the same point).
"""
import sys

OUT = sys.argv[1] if len(sys.argv) > 1 else "tools/state-assert-drive.pd"
DIR = sys.argv[2] if len(sys.argv) > 2 else "/tmp/cut-it-state-gate"

B, C = [], []


def obj(x, y, s):
    B.append("#X obj %d %d %s;" % (x, y, s))
    return len(B) - 1


def msg(x, y, s):
    B.append("#X msg %d %d %s;" % (x, y, s))
    return len(B) - 1


def txt(x, y, s, f=70):
    B.append("#X text %d %d %s, f %d;" % (x, y, s, f))
    return len(B) - 1


def con(a, ao, b, bi):
    C.append("#X connect %d %d %d %d;" % (a, ao, b, bi))


txt(20, 20, "GENERATED by state-assert-drive-gen.py -- DO NOT HAND-EDIT. "
    "Regenerated by state-assert.sh on every run \\, so an edit here is lost "
    "rather than wrong \\, which is the safer of the two.")

lb = obj(20, 140, "loadbang")
st = obj(20, 1500, "u_state %s" % DIR)

# ---------------------------------------------------------------- contributors
txt(1500, 140, "THE HONEST CONTRIBUTOR answers the save broadcast in the same "
    "call stack \\, which is what the contract requires and what every real one "
    "must do.")
rs = obj(1500, 320, "r state")
ro = obj(1500, 380, "route save restore")
good = msg(1500, 450, "put manual take-1 kick 36 snare 38")
gs = obj(1500, 500, "s state")
pr = obj(1900, 450, "print RESTORE")
con(rs, 0, ro, 0)
con(ro, 0, good, 0)
con(good, 0, gs, 0)
con(ro, 1, pr, 0)

txt(2250, 140, "THE DISHONEST ONE answers 5 ms late. It MUST NOT reach the "
    "file. If this key ever appears \\, the synchronous contract has silently "
    "stopped holding and every contributor written against it is at risk.")
bd = obj(2250, 380, "del 5")
bm = msg(2250, 450, "put manual late-key 999")
bs = obj(2250, 500, "s state")
con(ro, 0, bd, 0)
con(bd, 0, bm, 0)
con(bm, 0, bs, 0)

# ---------------------------------------------------------------------- driving
# (ms, message, bus) -- absolute times, one loadbang
STEPS = [
    (100, "put auto mode compose mode-1", "state"),
    (150, "put auto tempo 128", "state"),
    # the REPLACE case: same key again. A store that appended would pass every
    # other check here and still be wrong on the second save.
    (200, "put auto mode perform mode-4", "state"),
]
x = 20
for ms, m, bus in STEPS:
    d = obj(x, 260, "del %d" % ms)
    mm = msg(x, 320, m)
    ss = obj(x, 380, "s %s" % bus)
    con(lb, 0, d, 0)
    con(d, 0, mm, 0)
    con(mm, 0, ss, 0)
    x += 460

# the restore bang -- u_init's job in the real patch, and it ALSO arms the flush
txt(20, 700, "THE 3600 ms IS LOAD-BEARING AND MUST NOT BE SHORTENED. The bug this gate exists to catch armed the flush from a loadbang at 3000 ms while u_init restores at ~3500 ms -- so the write landed BEFORE the read. Bang the restore any earlier than 3000 here and that ordering never happens \\, the gate passes a broken patch \\, and it did exactly that once. THE RESTORE BANG ALSO ARMS THE AUTO FLUSH \\, which is "
    "deliberate rather than incidental: u_state must never write a file it has "
    "not yet read \\, or a boot would overwrite the previous session with its "
    "own defaults. Found on the Mac before it ever reached hardware.")
d = obj(20, 880, "del 3600")
rb = msg(20, 940, "bang")
con(lb, 0, d, 0)
con(d, 0, rb, 0)
con(rb, 0, st, 0)

# the commit. saveState is mother's name -- only a TEST driver may ever send it.
txt(1500, 700, "saveState IS mother.pd's RESERVED NAME and nothing in Cut It may "
    "send it. A gate driver is not deployed \\, so it is the one place that may.")
d = obj(1500, 880, "del 4200")
cm = msg(1500, 940, "bang")
cs = obj(1500, 1000, "s saveState")
con(lb, 0, d, 0)
con(d, 0, cm, 0)
con(cm, 0, cs, 0)

# self-quit: -send "pd quit" would return before any [del] fires
d = obj(2250, 880, "del 5400")
q = msg(2250, 940, "\\; pd quit")
con(lb, 0, d, 0)
con(d, 0, q, 0)

W = 2900
H = 1700
with open(OUT, "w") as fh:
    fh.write("#N canvas 20 20 %d %d 12;\n" % (W, H))
    fh.write("#X declare -path ../Cut\\ It;\n")
    fh.write("\n".join(B) + "\n")
    fh.write("\n".join(C) + "\n")
print("%s  %d boxes  %d cords  dir=%s" % (OUT, len(B), len(C), DIR))
